# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpQNHdGAJU3nmzN7EhF7Sb5g12aEVbLJ
"""

import gradio as gr
from transformers import MarianMTModel, MarianTokenizer

# Pretrained translation model
MODEL_NAME = "Helsinki-NLP/opus-mt-en-ar"

tokenizer = MarianTokenizer.from_pretrained(MODEL_NAME)
model = MarianMTModel.from_pretrained(MODEL_NAME)

def translate_text(text):
    if not text.strip():
        return ""

    inputs = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    translated = model.generate(**inputs)

    result = tokenizer.decode(
        translated[0],
        skip_special_tokens=True
    )

    return result



import streamlit as st

st.set_page_config(
    page_title="English → Arabic Translator",
    page_icon="🌐"
)

st.title("🌐 English → Arabic Translator")
st.write("Pretrained AI Translation Model")

text = st.text_area(
    "English Text",
    height=150,
    placeholder="Enter English text here..."
)

if st.button("Translate 🚀"):

    if text.strip():

        translation = translate_text(text)

        st.text_area(
            "Arabic Translation",
            value=translation,
            height=150
        )

    else:
        st.warning("Please enter some English text.")